name: Build & Deploy
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  call-Build:
    uses: bogdanbrudiu/HamSpecialEvent/.github/workflows/build.yml@main

  
