name: Build & Deploy
on: [push]
      
jobs:
  call-Build:
    uses: bogdanbrudiu/HamSpecialEvent/.github/workflows/build.yml@main

  PublisnAndDeploy:
    runs-on: ubuntu-latest
    name: Publish and Deploy
    environment: test
    
    steps:
      - name: Publish
        run: dotnet publish HamEvent/HamEvent.csproj --configuration Release --framework net7.0 --output ./publish --runtime win-x64 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false
      - name: Deploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          skip-directory-path:  '\\App_Data'


